version: '3'
services:
  app:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/coffeeShop
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"